package com.school.management.teacher.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.school.management.common.entity.BaseEntity;
import com.school.management.academic.entity.Department;
import com.school.management.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Teacher profile entity. Extends the base User via a 1-to-1 relationship.
 * Contains teacher-specific professional and academic information.
 */
@Entity
@Table(name = "teachers", uniqueConstraints = @UniqueConstraint(columnNames = "employee_id", name = "uk_teacher_employee_id"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Teacher extends BaseEntity {

    @Column(name = "employee_id", nullable = false, unique = true)
    private String employeeId; // e.g., "TCH-2024-001", auto-generated by service

    @Column(name = "qualification")
    private String qualification; // e.g., "M.Sc Mathematics", "B.Ed"

    @Column(name = "designation")
    private String designation; // e.g., "Senior Teacher", "HOD"

    @Column(name = "specialization")
    private String specialization;

    @Column(name = "experience_years")
    private Integer experienceYears;

    @Column(name = "joining_date")
    private LocalDate joiningDate;

    @Column(name = "is_active")
    @Builder.Default
    private Boolean isActive = true;

    // ── Relationships ──────────────────────────────────────────────────────────

    @JsonIgnore
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
    private Department department;

    @JsonIgnore
    @OneToMany(mappedBy = "teacher", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<com.school.management.academic.entity.SubjectAssignment> subjectAssignments = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "markedBy", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<com.school.management.attendance.entity.Attendance> markedAttendances = new ArrayList<>();
}
