package com.school.management.student.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.school.management.common.entity.BaseEntity;
import com.school.management.academic.entity.ClassGrade;
import com.school.management.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Student profile entity. Linked 1-to-1 with User.
 * Contains student-specific academic and personal information.
 */
@Entity
@Table(name = "students", uniqueConstraints = @UniqueConstraint(columnNames = "roll_number", name = "uk_student_roll_number"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Student extends BaseEntity {

    @Column(name = "roll_number", nullable = false, unique = true)
    private String rollNumber; // e.g., "STU-2024-001", auto-generated by service

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Column(name = "address", columnDefinition = "TEXT")
    private String address;

    @Column(name = "blood_group")
    private String bloodGroup;

    // ── Parent / Guardian Details ──────────────────────────────────────────────

    @Column(name = "parent_name")
    private String parentName;

    @Column(name = "parent_phone")
    private String parentPhone;

    @Column(name = "parent_email")
    private String parentEmail;

    @Column(name = "parent_occupation")
    private String parentOccupation;

    @Column(name = "emergency_contact")
    private String emergencyContact;

    // ── Academic ───────────────────────────────────────────────────────────────

    @Column(name = "admission_date")
    private LocalDate admissionDate;

    @Column(name = "previous_school")
    private String previousSchool;

    @Column(name = "is_active")
    @Builder.Default
    private Boolean isActive = true;

    // ── Relationships ──────────────────────────────────────────────────────────

    @JsonIgnore
    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "class_grade_id")
    private ClassGrade classGrade;

    // expose classGrade details in JSON for frontend display
    @Transient
    @com.fasterxml.jackson.annotation.JsonProperty("classGrade")
    public java.util.Map<String, Object> getClassGradeInfo() {
        if (classGrade == null) return null;
        java.util.Map<String, Object> m = new java.util.LinkedHashMap<>();
        m.put("id", classGrade.getId());
        m.put("gradeName", classGrade.getGradeName());
        m.put("section", classGrade.getSection());
        m.put("displayName", classGrade.getDisplayName());
        return m;
    }

    @JsonIgnore
    @OneToMany(mappedBy = "student", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<com.school.management.attendance.entity.Attendance> attendances = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "student", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<com.school.management.marks.entity.Mark> marks = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "student", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<com.school.management.fee.entity.FeePayment> feePayments = new ArrayList<>();

    // ── Transport ─────────────────────────────────────────────────────────────

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "route_stop_id")
    private com.school.management.transport.entity.RouteStop routeStop; // Student's bus pickup/drop stop

    // ── Transient API Exclusions ───────────────────────────────────────────────

    @Transient
    @com.fasterxml.jackson.annotation.JsonProperty("firstName")
    public String getFirstName() { return user != null ? user.getFirstName() : null; }

    @Transient
    @com.fasterxml.jackson.annotation.JsonProperty("lastName")
    public String getLastName() { return user != null ? user.getLastName() : null; }

    @Transient
    @com.fasterxml.jackson.annotation.JsonProperty("email")
    public String getEmail() { return user != null ? user.getEmail() : null; }

    @Transient
    @com.fasterxml.jackson.annotation.JsonProperty("gender")
    public com.school.management.common.enums.Gender getGender() { return user != null ? user.getGender() : null; }

    @Transient
    @com.fasterxml.jackson.annotation.JsonProperty("role")
    public com.school.management.common.enums.Role getRole() { return user != null ? user.getRole() : null; }
}
